# Generated by Django 5.1.1 on 2024-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_propmodel_img5_propmodel_img6_propmodel_img7_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propmodel",
            name="img5",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="propmodel",
            name="img6",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="propmodel",
            name="img7",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="propmodel",
            name="img8",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
