# Generated by Django 5.1.1 on 2024-11-28 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_propmodel_covivienda_remove_propmodel_forrent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propmodel",
            name="balcon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propmodel",
            name="doubleBedRooms",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propmodel",
            name="fullBathrooms",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propmodel",
            name="plazaGarage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="propmodel",
            name="simpleBathrooms",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="propmodel",
            name="simpleBedRooms",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
            preserve_default=False,
        ),
    ]
