# Generated by Django 5.1.4 on 2024-12-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_propmodel_balcon_propmodel_doublebedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propmodel',
            name='test_img',
            field=models.ImageField(default='assets/default.jpg', upload_to='assets'),
        ),
    ]
