# Generated by Django 5.1.4 on 2024-12-25 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_reviewmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propmodel',
            name='surface',
            field=models.IntegerField(blank=True, help_text='La superficie o área de la propiedad en metros cuadrados.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)], verbose_name='Superficie'),
        ),
    ]
