from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class propModel(models.Model):
    id = models.CharField(max_length= 100, primary_key= True, verbose_name="Identificator", help_text="El identificador de una casa, debe ser único, no pueden haber más de una casas con un mismo identificador.")
    title = models.CharField(max_length= 100, null=True, blank=True, verbose_name="Título", help_text="El titulo o nombre de la casa.")
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Descripción", help_text="La descripción de la casa.")
    location = models.CharField(max_length=200, null=True, blank=True, verbose_name="Ubicación", help_text="La ubicación o direcciónde la casa.")
    surface = models.DecimalField(validators=[MinValueValidator(0), MaxValueValidator(10000)], max_digits=5,decimal_places=2, blank=True, null=True, verbose_name="Superficie", help_text="La superficie o área de la casa.")
    type = models.CharField(max_length=50, null=True, blank=True, verbose_name="Tipo", help_text="El tipo de casa (piso, departamento, chalet, vivienda, etc.)")
    price = models.DecimalField(max_digits= 15, decimal_places= 2, null=True, blank=True, verbose_name="Precio", help_text="El precio de la casa.")
    numberOfRooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True, verbose_name="Habitaciones", help_text="El número de habitaciones de la casa.")
    doubleBedRooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True, verbose_name="Habitaciones dobles", help_text="El número de habitaciones dobles de la casa.")
    simpleBedRooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True, verbose_name="Habitaciones simples", help_text="El número de habitaciones simples de la casa.")
    numberOfBathR = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True, verbose_name="Baños", help_text="El número de baños de la casa.")
    fullBathrooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True, verbose_name="Baños completos", help_text="El número de baños completos de la casa.")
    simpleBathrooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)], null=True, blank=True, verbose_name="Baños simples", help_text="El número de baños simples de la casa.")
    img1 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 1")
    img2 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 2")
    img3 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 3")
    img4 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 4")
    img5 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 5")
    img6 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 6")
    img7 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 7")
    img8 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 8")
    img9 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 9")
    img10 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 10")
    img11 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 11")
    img12 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 12")
    img13 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 13")
    img14 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 14")
    img15 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 15")
    img16 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 16")
    img17 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 17")
    img18 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 18")
    img19 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 19")
    img20 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 20")
    img21 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 21")
    img22 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 22")
    img23 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 23")
    img24 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 24")
    img25 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 25")
    img26 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 26")
    img27 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 27")
    img28 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 28")
    img29 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 29")
    img30 = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen 30")
    mapImg = models.ImageField(upload_to='', default='', null=True, blank=True, verbose_name="Imagen de mapa")
    garage = models.BooleanField(default=False, verbose_name="Garaje")
    terraza = models.BooleanField(default=False, verbose_name="Terraza")
    trastero = models.BooleanField(default=False, verbose_name="Trastero")
    garden = models.BooleanField(default=False, verbose_name="Jardín")
    elevator = models.BooleanField(default=False, verbose_name="Ascensor")
    pool = models.BooleanField(default=False, verbose_name="Piscina")
    forSale = models.BooleanField(default=False, verbose_name="Para Venta")
    clientSale = models.BooleanField(default=False, verbose_name="Cliente Venta")
    plazaGarage = models.BooleanField(default=False, verbose_name="Plaza Garaje")
    balcon = models.BooleanField(default=False, verbose_name="Balcón")

    class Meta:
        verbose_name = "Propiedad"
        verbose_name_plural = "Propiedades"

class reviewModel(models.Model):
    name = models.CharField(max_length=100, primary_key= True)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    job = models.CharField(max_length= 50)
    title = models.CharField(max_length= 100)
    review = models.TextField(max_length= 300)
    img = models.CharField(max_length= 100)

class faqModel(models.Model):
    index = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5000)], primary_key=True)
    question = models.CharField(max_length=300)
    answer = models.TextField(max_length=2000)
