from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

class propModel(models.Model):
    id = models.CharField(max_length= 100, primary_key= True)
    title = models.CharField(max_length= 100)
    description = models.TextField(max_length=2000)
    location = models.CharField(max_length=200)
    surface = models.CharField(max_length=200)
    type = models.CharField(max_length=50)
    price = models.DecimalField(max_digits= 15, decimal_places= 2)
    numberOfRooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    doubleBedRooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    simpleBedRooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    numberOfBathR = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    fullBathrooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    simpleBathrooms = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    img1 = models.CharField(max_length=200)
    img2 = models.CharField(max_length=200)
    img3 = models.CharField(max_length=200)
    img4 = models.CharField(max_length=200)
    img5 = models.CharField(max_length=200, null=True, blank=True)
    img6 = models.CharField(max_length=200, null=True, blank=True)
    img7 = models.CharField(max_length=200, null=True, blank=True)
    img8 = models.CharField(max_length=200, null=True, blank=True)
    img9 = models.CharField(max_length=200, null=True, blank=True)
    img10 = models.CharField(max_length=200, null=True, blank=True)
    img11 = models.CharField(max_length=200, null=True, blank=True)
    img12 = models.CharField(max_length=200, null=True, blank=True)
    img13 = models.CharField(max_length=200, null=True, blank=True)
    img14 = models.CharField(max_length=200, null=True, blank=True)
    img15 = models.CharField(max_length=200, null=True, blank=True)
    img16 = models.CharField(max_length=200, null=True, blank=True)
    img17 = models.CharField(max_length=200, null=True, blank=True)
    img18 = models.CharField(max_length=200, null=True, blank=True)
    img19 = models.CharField(max_length=200, null=True, blank=True)
    img20 = models.CharField(max_length=200, null=True, blank=True)
    img21 = models.CharField(max_length=200, null=True, blank=True)
    img22 = models.CharField(max_length=200, null=True, blank=True)
    img23 = models.CharField(max_length=200, null=True, blank=True)
    img24 = models.CharField(max_length=200, null=True, blank=True)
    img25 = models.CharField(max_length=200, null=True, blank=True)
    img26 = models.CharField(max_length=200, null=True, blank=True)
    img27 = models.CharField(max_length=200, null=True, blank=True)
    img28 = models.CharField(max_length=200, null=True, blank=True)
    img29 = models.CharField(max_length=200, null=True, blank=True)
    img30 = models.CharField(max_length=200, null=True, blank=True)
    mapImg = models.CharField(max_length=200)
    garage = models.BooleanField(default=False)
    terraza = models.BooleanField(default=False)
    trastero = models.BooleanField(default=False)
    garden = models.BooleanField(default=False)
    elevator = models.BooleanField(default=False)
    pool = models.BooleanField(default=False)
    forSale = models.BooleanField(default=False)
    clientSale = models.BooleanField(default=False)
    plazaGarage = models.BooleanField(default=False)
    balcon = models.BooleanField(default=False)


class reviewModel(models.Model):
    name = models.CharField(max_length=100, primary_key= True)
    rating = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    job = models.CharField(max_length= 50)
    title = models.CharField(max_length= 100)
    review = models.TextField(max_length= 300)
    img = models.CharField(max_length= 100)

class faqModel(models.Model):
    index = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5000)], primary_key=True)
    question = models.CharField(max_length=300)
    answer = models.TextField(max_length=2000)
