services:
  django:
    build:
      context: ./backend
    container_name: django
    env_file:
      - .env
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - ./backend:/app
      - django_static:/app/staticfiles
    # Remove in production
    # ports:
    #   - "8000:8000"
    depends_on:
      - postgres
    networks:
      - calu-network

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Remove in production
    # ports:
    #   - "5433:5432"
    networks:
      - calu-network

  react:
    build:
      context: ./frontend
    container_name: react
    # entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - react_build:/app/build
    # Remove in production
    # ports:
    #   - "3000:3000"
    # stdin_open: true
    # tty: true
    networks:
      - calu-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "82:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - django_static:/app/staticfiles
      - react_build:/app/build
      - ./assets:/app/build/static/media/assets
    depends_on:
      - react
      - django
    networks:
      - calu-network

networks:
  calu-network:
    driver: bridge
    ipam:
      config: 
        - subnet: 172.16.238.0/24

volumes:
  postgres_data:
  django_static:
  react_build: